version: "3.8"
volumes:
  db-store:
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '${WEB_PORT}:80'
      - '${SSL_PORT}:443'
    links:
      - web
    restart: always
    environment:
      DOMAINS: '${DOMAIN} -> http://web:80'
      STAGE: '${STAGE}' # Don't use production until staging works
      # FORCE_RENEW: 'true'
    networks:
      - frontend
  web:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ${APP_PATH}:/var/www/html
    networks:
      - frontend
      - backend
  db:
    build: 
      context: .
      dockerfile: ./docker/db/Dockerfile
    volumes:
      - ./db/mysql_data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASS}
    networks:
      - backend
networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
